# Generated by Django 5.1.6 on 2025-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_interview", "0002_aiinterviewquestion_audio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinterviewresult",
            name="communication_score",
            field=models.FloatField(
                default=0.0, help_text="Communication skills score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="aiinterviewresult",
            name="problem_solving_score",
            field=models.FloatField(
                default=0.0, help_text="Problem solving skills score (0-100)"
            ),
        ),
    ]
